### ISSUE TITLE
Spotify Connecting Error (.enablespotify)

### ISSUE THREAD

**Issue by St3ph32** [HitaloM/PaperplaneMinimal#9]
**Describe the bug**
Trying to use the command .enablespotify it gives an error, and doesn't happen anything.

**To Reproduce**
1. Set Spotify settings in the config.
2. Use command .enablespotify.

**Expected behavior**
To change my BIO connecting to Spotify with what I am listening.

**Screenshots**
Not needed.

**Python Version**
3.8.5

**Additional context**
Error:

```2020-09-16 13:20:17,317 - userbot - ERROR - Exceeded 30 redirects.
Traceback (most recent call last):
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\events.py", line 66, in wrapper
    await func(check)
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\modules\spotify.py", line 118, in set_biostgraph
    await get_spotify_token()
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\modules\spotify.py", line 39, in get_spotify_token
    sptoken = st.start_session(USERNAME, PASSWORD)
  File "C:\Users\stefa\AppData\Roaming\Python\Python38\site-packages\spotify_token.py", line 18, in start_session
    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
2020-09-16 13:20:17,486 - telethon.client.updates - ERROR - Unhandled exception on wrapper
Traceback (most recent call last):
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\events.py", line 66, in wrapper
    await func(check)
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\modules\spotify.py", line 118, in set_biostgraph
    await get_spotify_token()
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\modules\spotify.py", line 39, in get_spotify_token
    sptoken = st.start_session(USERNAME, PASSWORD)
  File "C:\Users\stefa\AppData\Roaming\Python\Python38\site-packages\spotify_token.py", line 18, in start_session
    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stefa\AppData\Roaming\Python\Python38\site-packages\telethon\client\updates.py", line 443, in _dispatch_update
    await callback(event)
  File "C:\Users\stefa\OneDrive\Desktop\PaperplaneMinimal\userbot\events.py", line 126, in wrapper
    file.write(ftext)
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2326-2328: character maps to <undefined>```

**Comment by HitaloSama** [comment]
I am aware of this error, you can use the lastfm module instead of the Spotify module. Sorry!
